deploy:
  needs: test
  runs-on: ubuntu-latest
  if: contains(github.ref, 'tags')
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pip install -U build twine
    - name: Lint
      run: |
       black ./ --check
       flake8
       mypy example_package_le
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
      run: |
        python -m build
        twine upload dist/*
